project_name = "Final Project"
author = "張貓芋圓"

[home]
background = "assets/home/background.png"
button = "assets/home/button.png"
backpack_background = "assets/home/backpack_background.png" # 這時候不用出現 只是先設定

[professor.discussing] #event #中間不能空格
background = "assets/scene/background.png"
backpack_icon = "assets/scene/backpack_icon.png"
character_number = 2 #(0~3)
name = "L紀"
photo = "assets/scene/L紀.png"
favor = -2 #(-9~+9)
name = "TCC"
photo = "assets/scene/TCC.png"
favor = +5 #(-9~+9)

[[professor.discussing.dialogue]] #假如沒讀到就不用處理
dialog_box = "assets/scene/dialog_box.png"
string_number = 3 #(0~100) 0代表沒有對話
speaker = "L紀" #需要判錯是否有這個人物?
text = "text1"
speaker = "L紀"
text = "text2"
speaker = "TCC"
text = "text3"

[[professor.discussing.reply]] #沒讀到就不用處理
option1 = "text1"
next1 = "[event1]" #connect to other event（被中括號包起來）
option2 = "text2"
next2 = "[event2]"
option3 = "text3" 
next3 = "[event3]"

[[professor.discussing.backpack]] #每個event後面要再放當下情況的backpack
items_number = 5 #(0~9)
name = "water bottle"
photo = "assets/backpack/water_bottle.png"
description = "just a cute water bottle"
name = "pencil"
photo = "assets/backpack/pencil.png"
description = "it can write on anything"
name = "T-shirt"
photo = "assets/backpack/T-shirt.png"
description = "it is too small to L紀"
name = "watch"
photo = "assets/backpack/watch.png"
description = "apple watch, very expensive"
name = "christmas tree"
photo = "assets/backpack/christmas_tree.png"
description = "hahahappy christmas"
